feat: new option for block mining with local config
dashevo/mn-bootstrap pull request #137
Opened 2020-08-28 14:38 UTC by shuplenkov

## Issue being fixed or feature implemented

In order to avoid mining manually during local  config, we need to  enable miner for the local node

## What was done?

Added new option mine-blocks for start command

## How Has This Been Tested?

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2020-08-28 16:58 UTC, shumkov commented on src/commands/start.js
> +        throw new Error(`mine-blocks option supposed to work only with local network. Your network is ${config.get('network')}`);
`this.error` ?

2020-08-28 16:59 UTC, shumkov commented on src/commands/start.js
> +        throw new Error(`Invalid mine-blocks value ${mineBlocks}`);
`this.error` ?

2020-08-28 17:00 UTC, shumkov commented on src/commands/start.js
> +          title: 'Start mining',
Start miner

2020-08-28 17:02 UTC, shumkov commented on src/commands/start.js
> +  'mine-blocks': flagTypes.string({ description: 'new blocks mining interval for local node e.g. 5s', default: null }),
blocks mining interval for local node e.g. '5s' or '2.5m'

2020-08-28 17:03 UTC, shumkov commented on src/commands/start.js
> +            const address = privateKey.toAddress('regtest').toString();
Let's add an option `mine-blocks-address`? Could be useful.

2020-08-28 17:19 UTC, shumkov requested changes

2020-08-28 17:19 UTC, shumkov commented on src/commands/start.js
> +    if (mineBlocks !== null) {
Let's add new options to config that could be overwritten by command options.:
 - `core.miner.enabled=false`
 - `core.miner.interval="2.5m"`
 - `core.miner.address=null`

In this case, you don't need to pass them every time.

2020-08-31 08:17 UTC, shuplenkov commented on src/commands/start.js
> +        throw new Error(`mine-blocks option supposed to work only with local network. Your network is ${config.get('network')}`);
what does it mean `this.error`?

2020-08-31 08:17 UTC, shuplenkov commented on src/commands/start.js
> +        throw new Error(`Invalid mine-blocks value ${mineBlocks}`);
what does it mean `this.error`?

2020-08-31 14:16 UTC, shumkov commented on src/config/configJsonSchema.js
> +              type: 'string',
pattern: ^[0-9]+(\.[0-9]+)?(m|s|h)?$

2020-08-31 15:17 UTC, shumkov approved these changes
Cool! 👍

2020-08-31 15:25 UTC, merged