fix: various sentinel container errors on full nodes
dashevo/mn-bootstrap pull request #440
Opened 2021-10-01 15:47 UTC by strophy

## Issue being fixed or feature implemented

#270 Sentinel should not be started on full nodes, and should not be included in status output in `status:core` if it can never return a good status.

## What was done?

- Moved sentinel into a separate compose file
- Put conditions around sentinel status checks, so they only run on masternodes

## How Has This Been Tested?

Locally on testnet

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-10-01 15:55 UTC, shumkov requested changes

2021-10-01 15:55 UTC, shumkov commented on src/commands/status/services.js
> +    if (config.options.core.masternode.enable) {
Use get function

2021-10-01 15:55 UTC, shumkov commented on src/commands/status/core.js
> +    if (config.options.core.masternode.enable) {
Use get function

2021-10-01 16:20 UTC, strophy commented
Thanks, I had been using this notation everywhere in the status command, so now it is fixed everywhere 🚀

2021-10-04 11:48 UTC, shumkov approved these changes
LGTM! 👍

2021-10-04 11:52 UTC, merged