Feat format json
dashevo/mn-bootstrap pull request #462
Opened 2021-11-03 16:25 UTC by strophy

## Issue being fixed or feature implemented

We plan to implement tests on dashmate, which requires machine-readable output. This PR enables the `--format=json` flag for all `status` commands.

## What was done?

- Implement `json` format flag
- `strip-ansi` colors from `chalk`ed table output
- Refactor status commands

## How Has This Been Tested?

Locally against a testnet node, still waiting for sync

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-11-03 18:04 UTC, shumkov requested changes

2021-11-03 18:04 UTC, shumkov commented on src/commands/status/core.js
> +      Object.keys(outputRows).forEach((key) => {
I would recommend to use `Object.entries`

2021-11-03 18:04 UTC, shumkov commented on src/constants.js
> +  JSON: 'json',
Let's add plain format here as well

2021-11-03 18:04 UTC, shumkov commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
I think it must be enum: `plain` (by default) and `json`. Please add a description too.

2021-11-03 18:04 UTC, shumkov commented on src/status/outputStatusOverviewFactory.js
> +  async function outputStatusOverview(config, flags) {
The flags are command logic. I would pass here a specific argument with format to decouple it from commands.

2021-11-03 18:04 UTC, shumkov commented on src/commands/status/services.js
> +      outputRows.forEach((outputRow, i) => {
Let's do array of objects

2021-11-03 18:04 UTC, shumkov commented on src/commands/status/core.js
> +    if (getFormat(flags) === OUTPUT_FORMATS.JSON) {
I would recommend to extract this logic into function  `printers/printObject(object, format)` to DRY

2021-11-03 18:04 UTC, shumkov commented on src/commands/status/services.js
> +    if (getFormat(flags) === OUTPUT_FORMATS.JSON) {
This one you can extract to `printers/printArrayOfObjects(objects, format)`

2021-11-04 03:32 UTC, riongull commented
Thanks for this! I will be able to use this with the Incubator Discord bot.

2021-11-04 17:24 UTC, strophy commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
I used `table` instead so we have the option to add real `plain` output later (without table or ansi colours)

2021-11-04 18:57 UTC, shumkov commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
I was thinking that plain is just ascii (text).

2021-11-04 19:03 UTC, strophy commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
So the format enum contains `[plain, json, table]`?

2021-11-07 17:29 UTC, strophy commented
Sample command output: https://gist.github.com/strophy/26fa81c8218bdf76fff7bd49536d062a

2021-11-08 08:48 UTC, shumkov commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
I was thinking that output tables are “plain” (text) format. Not all commands have tables. Maybe I’m wrong..

2021-11-08 12:44 UTC, strophy commented on src/oclif/command/BaseCommand.js
> +  format: flagTypes.string(),
I see. Only status commands have table output, nearly all other commands use listr for output I think? Should we add JSON + plain output options for non-status commands?

2021-11-11 13:31 UTC, strophy commented
Closed in favor of https://github.com/dashevo/platform/pull/31/

2021-11-11 13:31 UTC, closed without merging